CLASS zjs_bp_bookingsupplement_u DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zjs_i_travel_u.
protected section.
private section.
ENDCLASS.



CLASS ZJS_BP_BOOKINGSUPPLEMENT_U IMPLEMENTATION.
ENDCLASS.
